# CRMEB 相关配置
crmeb:
  version: JAVA-MER-v1.9 # 当前代码版本
  domain: #配合swagger使用 # 待部署域名
  wechat-api-url:  #请求微信接口中专服务器
  asyncConfig: false #是否同步config表数据到redis
  asyncWeChatProgramTempList: false #是否同步小程序公共模板库
  imagePath: /Users/mac/tools/code/荆楚粮油云商城/jcly-shop/ # 服务器图片路径配置 斜杠结尾
  retailStoreBrokerageRatio: 30 #佣金返佣比例和上限
  activityStyleCachedTime: 10 #活动边框缓存周期 秒为单位，生产环境适当5-10分钟即可
  selectProductLimit: 100 # 商品选择 指定商品上线
  productTagCacheMinutes: 10 # 商品标签缓存分钟数

server:
  port: 20800

spring:
  profiles:
    #  配置的环境
    active: dev
    #  数据库配置
  servlet:
    multipart:
      max-file-size: 50MB #设置单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.199.1:3306/jcly-shop-dev?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&connectTimeout=60000&socketTimeout=60000
    username: root
    password: gsafety@123
    # Druid 连接池配置
    druid:
      # 初始化大小
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 用来检测连接是否有效的sql
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement
      pool-prepared-statements: true
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 连接泄漏监测
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
  redis:
    host: 47.98.199.1      # 地址
    port: 6389 # 端口
    password: gsafety@123 # 密码，建议生产环境开启
    timeout: 300000 # 连接超时时间（毫秒）
    database: 9  #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1